name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker.artodigital.id
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: docker.artodigital.id/opticseven:latest
          push: true

      - name: Deploy Stage
        if: github.ref == 'refs/heads/stage'
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}' \
          ${{vars.DEPLOYMENT_WEBHOOK_URL_STAGE}}${{ secrets.DEPLOYMENT_TOKEN_STAGE }}
